export enum TableName {
  TESTS = 'tests',
  TEST_DEMOGRAPHICS = 'test_demographics',
  TEST_COMPETITORS = 'test_competitors',
  TEST_VARIATIONS = 'test_variations',
  PRODUCTS = 'products',
  TEST_TIMES = 'test_times',
  RESPONSES_SURVEYS = 'responses_surveys',
  RESPONSES_COMPARISONS = 'responses_comparisons',
  RESPONSES_COMPARISONS_WALMART = 'responses_comparisons_walmart',
  INSIGHT_STATUS = 'insight_status',
  AI_INSIGHTS = 'ia_insights',
  TEST_SUMMARY = 'summary',
  PURCHASE_DRIVERS = 'purchase_drivers',
  COMPETITIVE_INSIGHTS = 'competitive_insights',
  COMPETITIVE_INSIGHTS_WALMART = 'competitive_insights_walmart',
  TESTERS_SESSION = 'testers_session',
  AMAZON_PRODUCTS = 'amazon_products',
  WALMART_PRODUCTS = 'walmart_products',
  PROFILES = 'profiles',
  EVENTS = 'events',
  COMPANY_INVITES = 'invites',
  COMPANY_CREDITS = 'company_credits',
  CREDIT_PAYMENTS = 'credit_payments',
  CREDIT_USAGE = 'credit_usage',
  COMPANIES = 'companies',
}

export enum Rpc {
  GET_COMPETITOR_INSIGHTS = 'get_competitive_insights_by_competitor',
  GET_COMPANY_TRANSACTION_HISTORY = 'get_company_transaction_history',
}
